### ISSUE TITLE
Discussion about the valve Point

### ISSUE THREAD

**Issue by redxeagle** [Timvdv/pimatic-zwave-usb#2]
Because the Danfoss doesnt support the valve as response you used the 40 as 100 percent and calculate this from the current wanted temperature.

The danfoss max temperature point is 28. Should this lowered to 28?

from:
-            @_setValve(parseInt(data.value) / 40 * 100) #40 == 100%
to:
+            @_setValve(parseInt(data.value) / 28 * 100) #40 == 100%

**Comment by Timvdv** [comment]
Nice find! Sure, go ahead 👍

**Comment by Timvdv** [comment]
fixed in https://github.com/Timvdv/pimatic-zwave-usb/pull/3
